### ISSUE TITLE
Consider Reddit ads

### ISSUE THREAD

**Issue by oksushi** [the-working-party/upstairs#15]
@ed-fast as a Reddit user, can you have a look at some subreddits that might be good to run some ads on? And it might be a good idea to make a post?

r/CoWorking etc

**Comment by ed-fast** [comment]
off the top of my head 
/r/Sydney
/r/Freelance

will look into this

**Comment by oksushi** [comment]
http://www.shopify.com.au/blog/15816508-how-to-make-your-first-1-000-with-reddit-ads

**Comment by oksushi** [comment]
/r/sydney/
